src/modulo-04-c-sharp/Locadora/Locadora.Web.MVC/Controllers/LocacaoController.cs
using Locadora.Dominio;
using Locadora.Dominio.Repositorio;
using Locadora.Web.MVC.Helpers;
using Locadora.Web.MVC.Models;
using Locadora.Web.MVC.Segurança;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Locadora.Web.MVC.Controllers
{
    public class LocacaoController : Controller
    {
        [Autorizador]
        public ActionResult Index(int id)
        {
            var repositorioJogo = FabricaDeModulos.CriarJogoRepositorio();
            var repositorioCliente = FabricaDeModulos.CriarJogoRepositorio();

            var jogo = repositorioJogo.BuscarPorId(id);

            ViewBag.Jogos = repositorioCliente.BuscarTodos();

            return View(new JogoLocacaoModel(jogo));
        }

        [Autorizador]
        public ActionResult Salvar(int Id, string nomeCliente)
        {
            var repositorioCliente = FabricaDeModulos.CriarClienteRepositorio();
            var repositorioLocacao = FabricaDeModulos.CriarLocacaoRepositorio();

            var cliente = repositorioCliente.BuscarPorNome(nomeCliente).First();
            var totalDeLocacoes = repositorioLocacao.BuscarTotalDeLocacoesPorCliente(cliente.Id);

            if (totalDeLocacoes < 3)
            {
                if (nomeCliente != "")
                {
                    repositorioLocacao.Criar(new Locacao(Id, cliente.Id));
                }
                else
                {
                    TempData["MensagemLocação"] = "Digite o nome de um cliente";
                }
            }
            else
            {
                TempData["MensagemLocação"] = "O cliente já possui três jogos locados!";
            }

            return RedirectToAction("Index", new { id = Id });
        }

    }
}

src/modulo-04-c-sharp/Locadora/Locadora.Web.MVC/Views/Locacao/Index.cshtml
@model JogoLocacaoModel
@{
    ViewBag.Title = "Index";
}

<style>

    body{
      background-color: #ECE9E9;
    }

    .pesquisa-cliente :first-child{
        border-radius: 3px;
        padding: 2px; 
     }

      .pesquisa-cliente :last-child{
        margin-bottom: 3px;
        padding: 3.2px 10px;
      }

      #pesquisaNome{
        width: 280px;
        height: 52px;
        display:inline-block;
        float:left
      }

</style>

@if (TempData["MensagemLocação"] != null)
{
    <div style="margin-top: 10px;" class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Falha!</strong> @TempData["MensagemLocação"]
    </div>
}

  <div>
      @Html.Partial("_InformacaoJogoLocacao", Model);
  </div>

<div class="pesquisa-cliente" style="position:absolute;top: 80%; right:20%;">
    @using (Html.BeginForm("Salvar", "Locacao", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.HiddenFor(m => m.Id)

        <div class="col-xs-6">
            <input id="pesquisaNome" class="form-control input-lg " type="text" name="nomeCliente" placeholder="Pesquisar cliente">
        </div>
        <div class="col-xs-1 col-lg-offset-5">
            <button type="submit" id="btn-locar" class="btn btn-lg btn-default" style="width: 160px;height: 50px; margin-left: -50px;">Fazer locação</button>
        </div>
    }
</div>

<script>
    $("#pesquisaNome").autocomplete({
        source: 'http://localhost:56771/Locacao/JogosAutocomplete'
    });
</script>