src/modulo-04-c-sharp/Locadora/Locadora.Web.MVC/Controllers/JogoController.cs
using Locadora.Dominio;
using Locadora.Dominio.Repositorio;
using Locadora.Web.MVC.Helpers;
using Locadora.Web.MVC.Models;
using Locadora.Web.MVC.Segurança;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Locadora.Web.MVC.Controllers
{
    public class JogoController : Controller
    {
        public ActionResult DetalhesJogo(int id)
        {
            var repositorio = FabricaDeModulos.CriarJogoRepositorio();

            var jogo = repositorio.BuscarPorId(id);

            return View(new JogoDetalhesModel(jogo));
        }

        [Autorizador(Roles = Permissao.PERMISSAO_MASTER)]
        public ActionResult Manter(int id = 0)
        {
            if (id > 0)
            {
                var repositorio = FabricaDeModulos.CriarJogoRepositorio();

                var jogo = repositorio.BuscarPorId(id);              

                return View(new JogoDetalhesModel(jogo));
            }

            return View();
        }

        public ActionResult Salvar(JogoDetalhesModel model)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);

            if (ModelState.IsValid)
            {
                IJogoRepositorio repositorio = new Repositorio.EF.JogoRepositorio();
                TempData["Status"] = true;


                if (!model.Id.HasValue)
                {
                    repositorio.Criar(model.ConverterParaJogo());
                    TempData["Mensagem"] = "Jogo cadastrado.";
                }
                else
                {
                    repositorio.Atualizar(model.ConverterParaJogo());
                    TempData["Mensagem"] = "Jogo atualizado.";
                }

                return RedirectToAction("JogosDisponiveis", "Relatorio");
            }
            else
            {
                return View("Manter", model);
            }
        }
    }
}

src/modulo-04-c-sharp/Locadora/Locadora.Web.MVC/Views/Jogo/DetalhesJogo.cshtml
@model JogoDetalhesModel
@{
    ViewBag.Title = "DetalhesJogo";
}


<style>

    html, body {
    width  : 100%;
    height : 100%;
}
    #overlay-back {
        position   : absolute;
        top        : 0;
        left       : 0;
        width      : 100%;
        height     : 100%;
        background : #000;
        opacity    : 0.8;
        filter     : alpha(opacity=60);
        z-index    : 5;
        display    : none;
    }

    #overlay {
        position : absolute;
        top      : 0;
        left     : 0;
        width    : 100%;
        height   : 100%;
        z-index  : 10;
        display  : none;
    }
    #btn-video:hover {
        opacity: 0.2;
        cursor:pointer;
    }

    .detalhes{
        overflow: hidden;
    }
   .descricao{
       padding-top:10px;
   }
</style>

<div class="jumbotron detalhes">
    <div class="col-xs-7">
        <h1 class="titulo">@Model.Nome <img id="btn-video" src="~/Content/Images/youtube.png" /></h1>

        <h2>Categoria: @Model.Categoria</h2>

        <p class="descricao">
            @Model.Descricao
        </p>
    </div>

    <img class="col-xs-5 imagem" src="/Content/Images/@(Model.Id + ".png")" />

    <div id="overlay-back"></div>
    <div id="overlay">

        <button id="fechar" class="btn btn-xs btn-danger" style="top:16%; right:28%; position: fixed">&times;</button>

        <div id="jogo-video" style="display:block; right:30%; top:16%; position:fixed">
            <iframe id="player" width="560" height="315" src="https://www.youtube.com/embed/6syG5YFGPeo" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>


    @section Scripts {
        <script>

            $('#btn-video').click(function () {
                $('#overlay, #overlay-back').fadeIn(500);
                $('#player').attr('src', 'https://www.youtube.com/embed/6syG5YFGPeo');
            });

            $('#fechar').on('click', function () {
                $('#overlay, #overlay-back').fadeOut(500);
                $('#player').attr('src', '');
            });

            $('#overlay').on('click', function () {
                $('#overlay, #overlay-back').fadeOut(500);
                $('#player').attr('src', '');
            });

        </script>
    }

</div>

src/modulo-04-c-sharp/Locadora/Locadora.Web.MVC/Views/Jogo/Manter.cshtml
@model JogoDetalhesModel
@{
    ViewBag.Title = "Manter";
}

@if(Model == null)
{
    <h2>Cadastrar jogo</h2>
}
else
{
    <h2>Editar jogo</h2>
}

@using (Html.BeginForm("Salvar", "Jogo", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false)

    @Html.HiddenFor(m => m.Id)

  <div class="form-group">
    @Html.LabelFor(m => m.Nome, new { @class = "col-sm-2 control-label" })
     <div class="col-sm-10">
        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Nome)           
      </div>       
  </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Preco, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.Preco, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Preco)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Categoria, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.EnumDropDownListFor(m => m.Categoria, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Categoria)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Selo, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.EnumDropDownListFor(m => m.Selo, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Selo)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Descricao, new { @class = "col-sm-2 control-label"})
        <div class="col-sm-10">
            @Html.TextAreaFor(m => m.Descricao, new { @class = "form-control", @rows = 6})
            @Html.ValidationMessageFor(m => m.Descricao)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Imagem, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-10">
            @Html.TextBoxFor(m => m.Imagem, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Imagem)
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </div>


@section Scripts {
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

}