src/modulo-04-c-sharp/Locadora/Locadora.Web.MVC/Controllers/DevolucaoController.cs
using Locadora.Web.MVC.Helpers;
using Locadora.Web.MVC.Models;
using Locadora.Web.MVC.Segurança;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Locadora.Web.MVC.Controllers
{
    [Autorizador]
    public class DevolucaoController : Controller
    {
        // GET: Devolucao
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Desalocar(int id)
        {
            var repositorioJogo = FabricaDeModulos.CriarJogoRepositorio();
            var repositorioLocacao = FabricaDeModulos.CriarLocacaoRepositorio();

            var jogo = repositorioJogo.BuscarPorId(id);
            var locacao = repositorioLocacao.BuscarPorId(id);

            repositorioLocacao.Desalocar(locacao);

            TempData["MensagemDevolucao"] = "Jogo devolvido";

            return View("Index");
        }

        [Autorizador]
        public ActionResult ExibirLocacao(string buscaLocacao)
        {
            var repositorioLocacao = FabricaDeModulos.CriarLocacaoRepositorio();

            var locacoes = repositorioLocacao.BuscarPorNomeDoJogo(buscaLocacao);

            return View("Index", new DevolucaoModel(locacoes));
        }
    }
}

src/modulo-04-c-sharp/Locadora/Locadora.Web.MVC/Controllers/RelatorioController.cs
using Locadora.Dominio.Repositorio;
using Locadora.Web.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Locadora.Web.MVC.Controllers
{
    public class RelatorioController : Controller
    {
        private IJogoRepositorio repositorio = new Repositorio.EF.JogoRepositorio();

        public ActionResult JogosDisponiveis(string busca)
        {
            var model = new RelatorioModel();
            var buscaJogos = repositorio.BuscarPorNome(busca);
            var jogos = buscaJogos;

            if (!string.IsNullOrWhiteSpace(busca))
            {
                if (buscaJogos.Count() != 0)
                {
                    jogos = buscaJogos;
                }
                else
                {
                    model.EncontrouResultados = false;
                }
            }
            else
            {
                jogos = repositorio.BuscarTodos();
            }
            

            foreach(var jogo in jogos)
            {
                var jogoModel = new JogoModel
                    (jogo.Id, jogo.Nome, jogo.Preco, jogo.Categoria.ToString(), jogo.Selo.ToString());
                model.Jogos.Add(jogoModel);
            }

            if(model.EncontrouResultados)
            {                      
                model.QuantidadeDeJogos = model.Jogos.Count();

                var maiorPreco = model.Jogos.Max(jogo => jogo.Preco);
                var menorPreco = model.Jogos.Min(jogo => jogo.Preco);
                model.JogoMaisCaro = model.Jogos.First(jogo => jogo.Preco == maiorPreco).Nome;
                model.JogoMaisBarato= model.Jogos.First(jogo => jogo.Preco == menorPreco).Nome;

                model.PrecoMedio = model.Jogos.Average(jogo => jogo.Preco);
            }

            return View(model);
        }
    }
}

src/modulo-04-c-sharp/Locadora/Locadora.Web.MVC/Views/Shared/_ImagemSelo.cshtml
@model string

@if (Model == "Ouro")
{
    <img class="img-selo" src="~/Content/Images/Ouro.png" />
}
else if (Model == "Prata")
{
    <img class="img-selo" src="~/Content/Images/Prata.png" />
}
else if (Model == "Bronze")
{
    <img class="img-selo" src="~/Content/Images/Bronze.png" />
}
else if (Model == "Ouro-lg")
{
    <img class="img-selo" src="~/Content/Images/Ouro-lg.png" />
}
else if (Model == "Prata-lg")
{
    <img class="img-selo" src="~/Content/Images/Ouro-lg.png" />
}
else if (Model == "Bronze-lg")
{
    <img class="img-selo" src="~/Content/Images/Ouro-lg.png" />
}

src/modulo-04-c-sharp/Locadora/Locadora.Web.MVC/Views/Shared/_InformacaoJogoLocacao.cshtml
@model JogoLocacaoModel


<style>
    .info-jogo{
        overflow:hidden;
    }

    .img-selo{
        position: absolute;
        top: -2%;
        right: -4%;
    }
</style>

<div style="width: 100%; position: absolute; right: 0%; background-color:#D4D4D4;" class="info-jogo jumbotron">

        @if (Model != null)
        {
            <div class="col-sm-5">
                <img src="https://legostevereviews.files.wordpress.com/2013/01/chrono-trigger-snes-box-350h.jpg" />

                @Html.Partial("_ImagemSelo", Model.Selo.ToString() + "-lg")

            </div>

            <div class="col-sm-offset-1 col-sm-6">
                <h1>@Model.Nome</h1>
                
                @if (Model.DataLocacao == null)
                {
                    <h2>@Model.Preco.ToString("c")</h2>
                    <h3>Previsão de entrega: @DateTime.Now.AddDays(Model.NumeroDeDiasDeEntrega).Date.ToString("dd/MM/yyyy")</h3>
                }
                else
                {
                    <h2>Valor total: @Model.PrecoTotal</h2>
                    <h3>Data locação: @Model.DataLocacao</h3>
                    <h3>Cliente: @Model.Cliente</h3>
                    <h3>Situação: @Model.Situacao</h3>
                    if (Model.Situacao == "Aberta")
                    {
                        <button id="btn-locar" class="btn btn-lg btn-info" style="display:inline-block;" onclick="location.href = '/Devolucao/Desalocar/@Model.IdLocacao'">Desalocar</button>
                    }
                }
            </div>
        }
</div>

src/modulo-04-c-sharp/Locadora/Locadora.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Locadora - @ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Login", "Index", "Login", new { area = "" }, new { @class = "navbar-brand lista-jogos" })
                @Html.ActionLink("Lista de jogos", "JogosDisponiveis", "Relatorio", new { area = "" }, new { @class = "navbar-brand lista-jogos" })
                @Html.ActionLink("Devolução de jogos", "Index", "Devolucao", new { area = "" }, new { @class = "navbar-brand lista-jogos" })
                
                <form class="pesquisa" action="~/Relatorio/JogosDisponiveis">
                    <input class="barra_pesquisa" type="text" name="busca" placeholder="Digite o nome de um jogo">
                    <input class="btn btn-default btn-md" type="submit" value="Pesquisar">
                </form>
                
                <style> 
                .lista-jogos{
                    margin-top: 2px;
                    font-size: 16px;
                }

                .pesquisa{     
                    float: right;
                    margin-top: 11px;
                    display: inline-block;
                    margin-right: -80%;
                }
                .pesquisa :first-child{
                    border-radius: 3px;
                    padding: 2px; 
                }
                .pesquisa :last-child{
                    margin-bottom: 3px;
                    padding: 3.2px 10px;
                }
                </style>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CWI Crescer</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("Scripts", false)
</body>
</html>